esphome:
  name: ${devicename}
  friendly_name: ${devicename}
  on_boot:
    priority: -10
    then:
      - delay: 15s 
      - deep_sleep.enter: deep_sleep_ctrl

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

logger:

api:
  password: "1"

ota:
  - platform: esphome
    password: "1"

wifi:
  ssid: "IoT"
  password: "InternetOfThings"
  fast_connect: true   

captive_portal:

i2c:
  sda: 33
  scl: 35
  scan: true

sensor:
  - platform: sht3xd
    temperature:
      name: "${devicename} Temperature"
    humidity:
      name: "${devicename} Humidity"
    address: 0x44
    update_interval: 10s

deep_sleep:
  id: deep_sleep_ctrl
  sleep_duration: 1min
