esphome:
  name: ${devicename}
  friendly_name: ${devicename}

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

logger:

api:
  password: "1"

ota:
  - platform: esphome
    password: "1"

wifi:
  ssid: "IoT"
  password: "InternetOfThings"

captive_portal:

i2c:
  sda: 33
  scl: 35
  scan: true

sensor:
  - platform: sht3xd
    temperature:
      name: "SHT3x Temperature"
    humidity:
      name: "SHT3x Humidity"
    address: 0x44
    update_interval: 300s  

#deep_sleep:
#  run_duration: 20s
#  sleep_duration: 5min
